spring.application.name=ploud
spring.profiles.default=local
server.tomcat.connection-timeout=${CONNECTION_TIME_OUT}
spring.mvc.async.request-timeout=${REQUEST_TIME_OUT}

spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=30

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway baseline ?? (?? ???? baseline?? ??)
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.baseline-description=Existing schema baseline


#Redis Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5s

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=1s



# MinIO ?? ??
minio.endpoint=http://localhost:9000
minio.endpoint.internal=http://localhost:9000
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET}
minio.bucket=test
minio.presign.expirySeconds=86400


#docker run --user root -d --name minio -e "MINIO_ROOT_USER=root" -e "MINIO_ROOT_PASSWORD=1234" -p 4380:9000 -p 4381:9001  -v minio:/data [quay.io/minio/minio](http://quay.io/minio/minio) server /data --console-address ":9001"

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

#MailService
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.debug_dev=${MAIL_DEBUG_DEV}
#front.path=http://localhost:5173/
front.path=https://kky.tail0a6d17.ts.net/ploud

#JWT
jwt.secret="${JWT_SECRET}

#encryptor
encrypt.secret="${ENCRYPT_SECRET}"


logging.level.root=INFO
logging.level.HTTP_ACCESS=INFO
